### ISSUE TITLE
RuntimeError: Text is not visible

### ISSUE THREAD

**Issue by khawar-islam** [clovaai/synthtiger#35]
While generating Korean dataset, I have added all given requirements like fonts and everything. I am using below command to generate dataset but getting an error between data generation process.

`python -m synthtiger -o results -w 4 -v examples/synthtiger/template.py SynthTiger examples/synthtiger/config_vertical.yaml
`

```
Generated 56 data
Generated 57 data
Generated 58 data
Generated 59 data
Generated 60 data
Traceback (most recent call last):
  File "/media/cvpr/CM_22/synthtiger/synthtiger/gen.py", line 71, in _generate
    data = template.generate()
  File "/media/cvpr/CM_22/synthtiger/examples/synthtiger/template.py", line 117, in generate
    image = _blend_images(fg_image, bg_image, self.visibility_check)
  File "/media/cvpr/CM_22/synthtiger/examples/synthtiger/template.py", line 246, in _blend_images
    raise RuntimeError("Text is not visible")
RuntimeError: Text is not visible

Generated 61 data
Generated 62 data
Generated 63 data
Generated 64 data
Generated 65 data
Generated 66 data
```

**Comment by moonbings** [comment]
Hi,

This engine tries to generate an image until the text is visible, and generates a specified number of images.
This error message means that the image is not saved when the text is not visible in the image.
So you may ignore this message.

Thanks.
